"""
다문화 정보 허브 — Mock 데이터
Phase 1 UI 개발용. 실제 서비스 연동 전까지 사용.
"""
from datetime import datetime, timedelta

_now = datetime.now()


def _days_ago(n: int) -> str:
    return (_now - timedelta(days=n)).strftime("%Y-%m-%d")


def _days_later(n: int) -> str:
    return (_now + timedelta(days=n)).strftime("%Y-%m-%d")


MOCK_NEWS = [
    {
        "id": 1,
        "title": "다문화가족지원법 시행령 개정안 입법예고",
        "content": "여성가족부는 다문화가족의 안정적 정착을 위해 지원 범위를 확대하는 내용의 시행령 개정안을 입법예고했다. 이번 개정안에는 결혼이민자의 직업교육 지원 확대와 자녀 이중언어 교육 강화 방안이 포함되어 있다.",
        "summary": "다문화가족지원법 시행령 개정으로 직업교육·이중언어 교육 지원이 확대됩니다.",
        "url": "https://www.mogef.go.kr/nw/enw/nw_enw_s001d.do?mid=mda700",
        "source": "연합뉴스",
        "category": "정책",
        "published": _days_ago(1),
        "is_bookmarked": False,
    },
    {
        "id": 2,
        "title": "경기도, 이주민 정착 지원 예산 30% 확대",
        "content": "경기도가 올해 이주민 정착 지원 예산을 전년 대비 30% 늘렸다. 한국어 교육, 취업 연계, 의료 통역 서비스 등이 강화된다.",
        "summary": "경기도 이주민 지원 예산 30% 증가. 한국어·취업·의료 서비스 확대.",
        "url": "https://www.gg.go.kr/bbs/boardList.do?bsIdx=464&menuId=2214",
        "source": "KBS",
        "category": "지역",
        "published": _days_ago(2),
        "is_bookmarked": True,
    },
    {
        "id": 3,
        "title": "UN, 한국 다문화 정책 모범사례로 선정",
        "content": "유엔 이주기구(IOM)가 한국의 사회통합프로그램을 이주민 통합 모범사례로 소개했다. 특히 한국어 교육과 문화 이해 프로그램이 높은 평가를 받았다.",
        "summary": "유엔 IOM, 한국 사회통합프로그램을 이주민 통합 모범사례로 선정.",
        "url": "https://www.iom.int/countries/republic-korea",
        "source": "뉴시스",
        "category": "국제",
        "published": _days_ago(3),
        "is_bookmarked": False,
    },
    {
        "id": 4,
        "title": "베트남 출신 이민자, 한국에서 창업 성공기",
        "content": "베트남 출신 결혼이민자 응웬 씨가 다문화 식당을 운영하며 연 매출 2억 원을 달성했다. 지자체 창업 지원 프로그램의 도움이 컸다고 전했다.",
        "summary": "베트남 출신 이민자의 창업 성공 사례. 지자체 지원이 핵심 요인.",
        "url": "https://www.liveinkorea.kr/portal/KOR/main/main.do",
        "source": "한겨레",
        "category": "사례",
        "published": _days_ago(5),
        "is_bookmarked": False,
    },
    {
        "id": 5,
        "title": "출입국관리법 개정으로 체류 외국인 권익 강화",
        "content": "법무부가 출입국관리법 개정안을 통해 체류 외국인의 권익 보호를 강화한다. 부당 해고 피해 외국인 근로자의 체류 자격 변경이 쉬워진다.",
        "summary": "출입국관리법 개정으로 외국인 근로자 권익 보호 강화.",
        "url": "https://www.law.go.kr/LSW/lsInfoP.do?lsiSeq=259775",
        "source": "연합뉴스",
        "category": "정책",
        "published": _days_ago(0),
        "is_bookmarked": True,
    },
    {
        "id": 6,
        "title": "서울시, 다문화가정 자녀 방과후 프로그램 확대",
        "content": "서울시교육청이 다문화가정 자녀를 위한 방과후 프로그램을 전 학교로 확대한다. 이중언어 교육과 또래 멘토링이 포함된다.",
        "summary": "서울시 다문화가정 자녀 방과후 프로그램 전 학교 확대 시행.",
        "url": "https://www.sen.go.kr/web/services/bbs/bbsList.action?bbsBean.bbsCd=94",
        "source": "서울신문",
        "category": "지역",
        "published": _days_ago(1),
        "is_bookmarked": False,
    },
]

MOCK_LAWS = [
    {
        "id": 1,
        "law_code": "LAW-001",
        "name": "다문화가족지원법",
        "category": "다문화",
        "content": "제1조(목적) 이 법은 다문화가족 구성원이 안정적인 가족생활을 영위하고 사회구성원으로서의 역할과 책임을 다할 수 있도록 함으로써 이들의 삶의 질 향상과 사회통합에 이바지함을 목적으로 한다.\n\n제2조(정의) 이 법에서 사용하는 용어의 뜻은 다음과 같다.\n1. \"다문화가족\"이란 다음 각 목의 어느 하나에 해당하는 가족을 말한다.\n  가. 「재한외국인 처우 기본법」 제2조제3호의 결혼이민자와 「국적법」 제2조부터 제4조까지의 규정에 따라 대한민국 국적을 취득한 자로 이루어진 가족\n  나. 「국적법」 제3조 및 제4조에 따라 대한민국 국적을 취득한 자와 같은 법 제2조부터 제4조까지의 규정에 따라 대한민국 국적을 취득한 자로 이루어진 가족",
        "summary": "다문화가족의 안정적 가족생활과 사회통합을 위한 지원 법률. 결혼이민자와 귀화자 가족을 대상으로 교육·상담·의료 등 지원.",
        "amended_date": "2024-07-01",
        "effective_date": "2024-10-01",
        "is_bookmarked": True,
    },
    {
        "id": 2,
        "law_code": "LAW-002",
        "name": "재한외국인 처우 기본법",
        "category": "다문화",
        "content": "제1조(목적) 이 법은 재한외국인에 대한 처우 등에 관한 기본적인 사항을 정함으로써 재한외국인이 대한민국 사회에 적응하여 개인의 능력을 충분히 발휘할 수 있도록 하고, 대한민국 국민과 재한외국인이 서로를 이해하고 존중하는 사회 환경을 만들어 대한민국의 발전과 사회통합에 이바지함을 목적으로 한다.",
        "summary": "재한외국인의 사회 적응과 국민 간 상호 존중을 위한 기본법. 결혼이민자·외국인근로자·난민 등의 처우 기준 규정.",
        "amended_date": "2023-12-15",
        "effective_date": "2024-03-15",
        "is_bookmarked": False,
    },
    {
        "id": 3,
        "law_code": "LAW-003",
        "name": "출입국관리법",
        "category": "출입국",
        "content": "제1조(목적) 이 법은 대한민국에 입국하거나 대한민국에서 출국하는 모든 국민 및 외국인의 출입국관리를 통한 안전한 국경관리, 대한민국에 체류하는 외국인의 체류관리와 사회통합 등에 관한 사항을 규정함을 목적으로 한다.",
        "summary": "외국인의 입출국·체류 관리에 관한 법률. 비자, 체류 자격, 강제 퇴거 등 규정.",
        "amended_date": "2025-01-10",
        "effective_date": "2025-04-10",
        "is_bookmarked": False,
    },
    {
        "id": 4,
        "law_code": "LAW-004",
        "name": "국적법",
        "category": "국적",
        "content": "제1조(목적) 이 법은 대한민국의 국적의 취득과 상실에 관한 사항을 규정함을 목적으로 한다.\n\n제2조(출생에 의한 국적 취득) ① 다음 각 호의 어느 하나에 해당하는 자는 출생과 동시에 대한민국 국적을 취득한다.\n1. 출생 당시에 부 또는 모가 대한민국의 국민인 자",
        "summary": "대한민국 국적 취득·상실에 관한 법률. 출생, 귀화, 국적 회복 등의 요건 규정.",
        "amended_date": "2024-05-20",
        "effective_date": "2024-11-20",
        "is_bookmarked": True,
    },
    {
        "id": 5,
        "law_code": "LAW-005",
        "name": "외국인근로자의 고용 등에 관한 법률",
        "category": "출입국",
        "content": "제1조(목적) 이 법은 외국인근로자를 체계적으로 도입·관리함으로써 원활한 인력수급 및 국민경제의 균형 있는 발전을 도모함을 목적으로 한다.",
        "summary": "외국인 근로자 고용 허가제 운영 법률. 고용 절차, 근로 조건, 권리 보호 등 규정.",
        "amended_date": "2024-03-01",
        "effective_date": "2024-06-01",
        "is_bookmarked": False,
    },
    {
        "id": 6,
        "law_code": "LAW-006",
        "name": "난민법",
        "category": "다문화",
        "content": "제1조(목적) 이 법은 「난민의 지위에 관한 1951년 협약」 및 「난민의 지위에 관한 1967년 의정서」 등에 따라 난민의 지위와 처우 등에 관한 사항을 정함을 목적으로 한다.",
        "summary": "난민 인정 절차와 난민 인정자의 처우에 관한 법률. 난민 신청, 심사, 재정착 등 규정.",
        "amended_date": "2023-09-01",
        "effective_date": "2024-01-01",
        "is_bookmarked": False,
    },
]

MOCK_SUPPORT = [
    {
        "id": 1,
        "name": "다문화가족 방문교육 서비스",
        "description": "결혼이민자 및 다문화가족 구성원에게 한국어 교육, 부모 교육, 자녀 생활 서비스를 가정 방문을 통해 제공합니다.",
        "organizer": "여성가족부",
        "org_type": "중앙",
        "region": "전국",
        "target_group": "결혼이민자, 다문화가족",
        "benefit": "주 2회 방문교육 (한국어, 부모교육)",
        "apply_start": _days_ago(30),
        "apply_end": _days_later(60),
        "contact": "1577-1366",
        "url": "https://www.liveinkorea.kr",
        "is_bookmarked": True,
    },
    {
        "id": 2,
        "name": "이중언어 환경조성 사업",
        "description": "다문화가족 자녀의 이중언어 능력을 키우기 위한 가정 내 이중언어 환경 조성 프로그램입니다.",
        "organizer": "여성가족부",
        "org_type": "중앙",
        "region": "전국",
        "target_group": "다문화가족 자녀 (만 12세 이하)",
        "benefit": "이중언어 코치 파견 (주 1~2회)",
        "apply_start": _days_ago(15),
        "apply_end": _days_later(45),
        "contact": "1577-1366",
        "url": "https://www.liveinkorea.kr",
        "is_bookmarked": False,
    },
    {
        "id": 3,
        "name": "경기도 이주민 취업 연계 프로그램",
        "description": "경기도 거주 이주민을 대상으로 직업 교육, 자격증 취득 지원, 취업 알선 서비스를 제공합니다.",
        "organizer": "경기도청",
        "org_type": "지자체",
        "region": "경기",
        "target_group": "경기도 거주 이주민",
        "benefit": "직업교육 + 자격증 응시료 + 취업 알선",
        "apply_start": _days_ago(10),
        "apply_end": _days_later(20),
        "contact": "031-120",
        "url": "https://www.gg.go.kr",
        "is_bookmarked": False,
    },
    {
        "id": 4,
        "name": "서울시 다문화가정 의료비 지원",
        "description": "서울시 거주 다문화가정의 건강검진 및 의료비를 지원합니다. 긴급 의료 통역 서비스도 포함됩니다.",
        "organizer": "서울특별시",
        "org_type": "지자체",
        "region": "서울",
        "target_group": "서울 거주 다문화가정",
        "benefit": "건강검진 무료, 의료비 연 100만원 한도 지원",
        "apply_start": _days_ago(5),
        "apply_end": _days_later(90),
        "contact": "02-120",
        "url": "https://www.seoul.go.kr",
        "is_bookmarked": True,
    },
    {
        "id": 5,
        "name": "사회통합프로그램 (KIIP)",
        "description": "법무부에서 운영하는 이민자 사회통합 교육 프로그램. 한국어와 한국 사회 이해 과정을 무료로 제공합니다.",
        "organizer": "법무부",
        "org_type": "중앙",
        "region": "전국",
        "target_group": "합법 체류 외국인",
        "benefit": "한국어·한국문화 교육 무료, 귀화 시험 면제 혜택",
        "apply_start": _days_ago(60),
        "apply_end": _days_later(120),
        "contact": "1345",
        "url": "https://www.socinet.go.kr",
        "is_bookmarked": False,
    },
]

# 대시보드 KPI
MOCK_DASHBOARD = {
    "news_count": len(MOCK_NEWS),
    "law_count": len(MOCK_LAWS),
    "support_count": len(MOCK_SUPPORT),
    "today_news": sum(1 for n in MOCK_NEWS if n["published"] == _days_ago(0)),
    "closing_soon": sum(1 for s in MOCK_SUPPORT if 0 <= (datetime.strptime(s["apply_end"], "%Y-%m-%d") - _now).days <= 7),
    "bookmarked": sum(1 for n in MOCK_NEWS if n["is_bookmarked"]) + sum(1 for l in MOCK_LAWS if l["is_bookmarked"]) + sum(1 for s in MOCK_SUPPORT if s["is_bookmarked"]),
    "last_update": _now.strftime("%Y-%m-%d %H:%M"),
}
